export interface ComponentDoc {
  name: string;
  tagline: string;
  props: { name: string; type: string; default: string; desc: string }[];
  examples: { label: string; code: string; output: string }[];
  classMap: { prop: string; value: string; classes: string }[];
}

export const COMPONENT_DOCS: ComponentDoc[] = [
  {
    name: "lk-center",
    tagline: "Center content on both axes. The #1 CSS pain point, solved — no JavaScript required.",
    props: [
      { name: "fill", type: "boolean", default: "off", desc: "Grow to fill available space in the parent flex container (flex: 1 1 0%)" },
      { name: "full-height", type: "boolean", default: "off", desc: "Force a minimum full-viewport height (min-height: 100vh)" },
      { name: "horizontal", type: "boolean", default: "off", desc: "Center only on the x-axis" },
      { name: "vertical", type: "boolean", default: "off", desc: "Center only on the y-axis" },
      { name: "inline", type: "boolean", default: "off", desc: "Use inline-flex instead of flex" },
    ],
    examples: [
      { label: "Basic center", code: "<lk-center>\n  <h1>Centered</h1>\n</lk-center>", output: "display: flex; flex-direction: column; align-items: center; justify-content: center" },
      { label: "Full page", code: "<lk-center full-height>\n  <form>Login</form>\n</lk-center>", output: "display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh" },
      { label: "Horizontal only", code: "<lk-center horizontal>\n  <nav>Menu</nav>\n</lk-center>", output: "display: flex; flex-direction: column; align-items: center; justify-content: flex-start" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: column; align-items: center; justify-content: center" },
      { prop: "fill", value: "(present)", classes: "flex: 1 1 0%" },
      { prop: "full-height", value: "(present)", classes: "min-height: 100vh" },
      { prop: "horizontal", value: "(present)", classes: "justify-content: flex-start" },
      { prop: "vertical", value: "(present)", classes: "align-items: stretch" },
      { prop: "inline", value: "(present)", classes: "display: inline-flex" },
    ],
  },
  {
    name: "lk-stack",
    tagline: "Vertical flex column with consistent spacing.",
    props: [
      { name: "gap", type: "GapSize", default: "md (1rem)", desc: "Space between children" },
      { name: "align", type: "Align", default: "stretch", desc: "Cross-axis alignment (align-items)" },
      { name: "justify", type: "Justify", default: "start", desc: "Main-axis alignment (justify-content)" },
      { name: "center", type: "boolean", default: "off", desc: "Center both axes (shorthand)" },
      { name: "fill", type: "boolean", default: "off", desc: "Grow to fill available space (flex: 1 1 0%)" },
      { name: "full-height", type: "boolean", default: "off", desc: "Force a minimum full-viewport height (min-height: 100vh)" },
      { name: "padding", type: "Padding", default: "none", desc: "Internal padding" },
      { name: "wrap", type: "boolean", default: "off", desc: "Allow children to wrap" },
    ],
    examples: [
      { label: "Default stack", code: "<lk-stack>\n  <div>Item</div>\n  <div>Item</div>\n</lk-stack>", output: "display: flex; flex-direction: column; gap: 1rem; align-items: stretch; justify-content: flex-start" },
      { label: "Centered stack", code: '<lk-stack center gap="lg">\n  <img alt="avatar">\n  <span>Name</span>\n</lk-stack>', output: "display: flex; flex-direction: column; gap: 1.5rem; align-items: center; justify-content: center" },
      { label: "With padding", code: '<lk-stack padding="lg" gap="sm">\n  <input>\n  <input>\n</lk-stack>', output: "display: flex; flex-direction: column; gap: 0.5rem; align-items: stretch; justify-content: flex-start; padding: 1.5rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: column; gap: 1rem; align-items: stretch; justify-content: flex-start" },
      { prop: "gap", value: "none", classes: "gap: 0" },
      { prop: "gap", value: "xs", classes: "gap: 0.25rem" },
      { prop: "gap", value: "sm", classes: "gap: 0.5rem" },
      { prop: "gap", value: "md (default)", classes: "gap: 1rem" },
      { prop: "gap", value: "lg", classes: "gap: 1.5rem" },
      { prop: "gap", value: "xl", classes: "gap: 2rem" },
      { prop: "gap", value: "2xl", classes: "gap: 3rem" },
      { prop: "gap", value: "3xl", classes: "gap: 4rem" },
      { prop: "align", value: "start", classes: "align-items: flex-start" },
      { prop: "align", value: "center", classes: "align-items: center" },
      { prop: "align", value: "end", classes: "align-items: flex-end" },
      { prop: "align", value: "stretch (default)", classes: "align-items: stretch" },
      { prop: "align", value: "baseline", classes: "align-items: baseline" },
      { prop: "justify", value: "start (default)", classes: "justify-content: flex-start" },
      { prop: "justify", value: "center", classes: "justify-content: center" },
      { prop: "justify", value: "end", classes: "justify-content: flex-end" },
      { prop: "justify", value: "between", classes: "justify-content: space-between" },
      { prop: "justify", value: "around", classes: "justify-content: space-around" },
      { prop: "justify", value: "evenly", classes: "justify-content: space-evenly" },
      { prop: "center", value: "(present)", classes: "align-items: center; justify-content: center" },
      { prop: "fill", value: "(present)", classes: "flex: 1 1 0%" },
      { prop: "full-height", value: "(present)", classes: "min-height: 100vh" },
      { prop: "wrap", value: "(present)", classes: "flex-wrap: wrap" },
      { prop: "padding", value: "xs", classes: "padding: 0.25rem" },
      { prop: "padding", value: "sm", classes: "padding: 0.5rem" },
      { prop: "padding", value: "md", classes: "padding: 1rem" },
      { prop: "padding", value: "lg", classes: "padding: 1.5rem" },
      { prop: "padding", value: "xl", classes: "padding: 2rem" },
      { prop: "padding", value: "2xl", classes: "padding: 3rem" },
    ],
  },
  {
    name: "lk-row",
    tagline: "Horizontal flex row. Same attributes as lk-stack, different axis.",
    props: [
      { name: "gap", type: "GapSize", default: "md (1rem)", desc: "Space between children" },
      { name: "align", type: "Align", default: "center", desc: "Cross-axis alignment (align-items)" },
      { name: "justify", type: "Justify", default: "start", desc: "Main-axis alignment (justify-content)" },
      { name: "center", type: "boolean", default: "off", desc: "Center both axes" },
      { name: "wrap", type: "boolean", default: "off", desc: "Allow children to wrap" },
      { name: "reverse", type: "boolean", default: "off", desc: "Reverse direction (flex-direction: row-reverse)" },
      { name: "padding", type: "Padding", default: "none", desc: "Internal padding" },
    ],
    examples: [
      { label: "Button group", code: '<lk-row gap="sm">\n  <button>Save</button>\n  <button>Cancel</button>\n</lk-row>', output: "display: flex; flex-direction: row; gap: 0.5rem; align-items: center; justify-content: flex-start" },
      { label: "Nav bar", code: '<lk-row justify="between">\n  <span>Logo</span>\n  <nav>Menu</nav>\n</lk-row>', output: "display: flex; flex-direction: row; gap: 1rem; align-items: center; justify-content: space-between" },
      { label: "Wrapped tags", code: '<lk-row wrap gap="xs">\n  <span>Tag</span>\n  <span>Tag</span>\n</lk-row>', output: "display: flex; flex-direction: row; gap: 0.25rem; align-items: center; justify-content: flex-start; flex-wrap: wrap" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: row; gap: 1rem; align-items: center; justify-content: flex-start" },
      { prop: "gap", value: "none", classes: "gap: 0" },
      { prop: "gap", value: "xs", classes: "gap: 0.25rem" },
      { prop: "gap", value: "sm", classes: "gap: 0.5rem" },
      { prop: "gap", value: "md (default)", classes: "gap: 1rem" },
      { prop: "gap", value: "lg", classes: "gap: 1.5rem" },
      { prop: "gap", value: "xl", classes: "gap: 2rem" },
      { prop: "gap", value: "2xl", classes: "gap: 3rem" },
      { prop: "gap", value: "3xl", classes: "gap: 4rem" },
      { prop: "align", value: "start", classes: "align-items: flex-start" },
      { prop: "align", value: "center (default)", classes: "align-items: center" },
      { prop: "align", value: "end", classes: "align-items: flex-end" },
      { prop: "align", value: "stretch", classes: "align-items: stretch" },
      { prop: "align", value: "baseline", classes: "align-items: baseline" },
      { prop: "justify", value: "start (default)", classes: "justify-content: flex-start" },
      { prop: "justify", value: "center", classes: "justify-content: center" },
      { prop: "justify", value: "end", classes: "justify-content: flex-end" },
      { prop: "justify", value: "between", classes: "justify-content: space-between" },
      { prop: "justify", value: "around", classes: "justify-content: space-around" },
      { prop: "justify", value: "evenly", classes: "justify-content: space-evenly" },
      { prop: "center", value: "(present)", classes: "align-items: center; justify-content: center" },
      { prop: "wrap", value: "(present)", classes: "flex-wrap: wrap" },
      { prop: "reverse", value: "(present)", classes: "flex-direction: row-reverse" },
      { prop: "padding", value: "xs", classes: "padding: 0.25rem" },
      { prop: "padding", value: "sm", classes: "padding: 0.5rem" },
      { prop: "padding", value: "md", classes: "padding: 1rem" },
      { prop: "padding", value: "lg", classes: "padding: 1.5rem" },
      { prop: "padding", value: "xl", classes: "padding: 2rem" },
      { prop: "padding", value: "2xl", classes: "padding: 3rem" },
    ],
  },
  {
    name: "lk-box",
    tagline: "Generic block container. Fills space, holds content.",
    props: [
      { name: "fill", type: "boolean", default: "off", desc: "Expand to fill available space (flex: 1 1 0%)" },
      { name: "padding", type: "Padding", default: "none", desc: "Internal padding" },
    ],
    examples: [
      { label: "Fill space", code: "<lk-box fill>\n  <div>Content</div>\n</lk-box>", output: "display: block; flex: 1 1 0%" },
      { label: "Padded fill", code: '<lk-box fill padding="lg">\n  <div>Content</div>\n</lk-box>', output: "display: block; flex: 1 1 0%; padding: 1.5rem" },
      { label: "Padded box", code: '<lk-box padding="md">\n  <div>Content</div>\n</lk-box>', output: "display: block; padding: 1rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: block" },
      { prop: "fill", value: "(present)", classes: "flex: 1 1 0%" },
      { prop: "padding", value: "xs", classes: "padding: 0.25rem" },
      { prop: "padding", value: "sm", classes: "padding: 0.5rem" },
      { prop: "padding", value: "md", classes: "padding: 1rem" },
      { prop: "padding", value: "lg", classes: "padding: 1.5rem" },
      { prop: "padding", value: "xl", classes: "padding: 2rem" },
      { prop: "padding", value: "2xl", classes: "padding: 3rem" },
    ],
  },
  {
    name: "lk-spread",
    tagline: "Push children to opposite ends. Headers, footers, toolbars.",
    props: [
      { name: "align", type: "Align", default: "center", desc: "Cross-axis alignment (align-items)" },
      { name: "padding", type: "Padding", default: "none", desc: "Internal padding" },
    ],
    examples: [
      { label: "Header", code: "<lk-spread>\n  <span>Logo</span>\n  <nav>Menu</nav>\n</lk-spread>", output: "display: flex; flex-direction: row; justify-content: space-between; align-items: center" },
      { label: "Footer", code: '<lk-spread padding="sm">\n  <span>Copyright</span>\n  <span>Links</span>\n</lk-spread>', output: "display: flex; flex-direction: row; justify-content: space-between; align-items: center; padding: 0.5rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: row; justify-content: space-between; align-items: center" },
      { prop: "align", value: "start", classes: "align-items: flex-start" },
      { prop: "align", value: "center (default)", classes: "align-items: center" },
      { prop: "align", value: "end", classes: "align-items: flex-end" },
      { prop: "align", value: "stretch", classes: "align-items: stretch" },
      { prop: "align", value: "baseline", classes: "align-items: baseline" },
      { prop: "padding", value: "xs", classes: "padding: 0.25rem" },
      { prop: "padding", value: "sm", classes: "padding: 0.5rem" },
      { prop: "padding", value: "md", classes: "padding: 1rem" },
      { prop: "padding", value: "lg", classes: "padding: 1.5rem" },
      { prop: "padding", value: "xl", classes: "padding: 2rem" },
      { prop: "padding", value: "2xl", classes: "padding: 3rem" },
    ],
  },
  {
    name: "lk-grid",
    tagline: "CSS Grid with simple column counts.",
    props: [
      { name: "cols", type: "1-12", default: "1", desc: "Number of columns" },
      { name: "rows", type: "1-6", default: "auto", desc: "Number of explicit rows" },
      { name: "gap", type: "GapSize", default: "md (1rem)", desc: "Gap between grid items" },
      { name: "col-gap", type: "GapSize", default: "—", desc: "Column gap only (column-gap)" },
      { name: "row-gap", type: "GapSize", default: "—", desc: "Row gap only (row-gap)" },
      { name: "flow", type: "row | col | dense", default: "row", desc: "Grid auto-flow direction" },
      { name: "place-items", type: "start | center | end | stretch", default: "—", desc: "Shorthand for align + justify items" },
      { name: "responsive", type: "boolean", default: "off", desc: "Auto-responsive columns via auto-fit" },
      { name: "--lk-min-child-width", type: "length (custom prop)", default: "250px", desc: "Min child width when responsive (set inline via style)" },
    ],
    examples: [
      { label: "3-column", code: '<lk-grid cols="3" gap="md">\n  <div>Card</div>\n  <div>Card</div>\n  <div>Card</div>\n</lk-grid>', output: "display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 1rem" },
      { label: "Dashboard", code: '<lk-grid cols="4" gap="sm">\n  <div>Stat</div>\n  <div>Stat</div>\n  <div>Stat</div>\n  <div>Stat</div>\n</lk-grid>', output: "display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 0.5rem" },
      { label: "Responsive", code: '<lk-grid responsive gap="md" style="--lk-min-child-width: 200px">\n  <div>Card</div>\n  <div>Card</div>\n</lk-grid>', output: "display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: grid; grid-template-columns: repeat(1, minmax(0, 1fr)); gap: 1rem" },
      { prop: "cols", value: "1", classes: "grid-template-columns: repeat(1, minmax(0, 1fr))" },
      { prop: "cols", value: "2", classes: "grid-template-columns: repeat(2, minmax(0, 1fr))" },
      { prop: "cols", value: "3", classes: "grid-template-columns: repeat(3, minmax(0, 1fr))" },
      { prop: "cols", value: "4", classes: "grid-template-columns: repeat(4, minmax(0, 1fr))" },
      { prop: "cols", value: "5", classes: "grid-template-columns: repeat(5, minmax(0, 1fr))" },
      { prop: "cols", value: "6", classes: "grid-template-columns: repeat(6, minmax(0, 1fr))" },
      { prop: "cols", value: "7", classes: "grid-template-columns: repeat(7, minmax(0, 1fr))" },
      { prop: "cols", value: "8", classes: "grid-template-columns: repeat(8, minmax(0, 1fr))" },
      { prop: "cols", value: "9", classes: "grid-template-columns: repeat(9, minmax(0, 1fr))" },
      { prop: "cols", value: "10", classes: "grid-template-columns: repeat(10, minmax(0, 1fr))" },
      { prop: "cols", value: "11", classes: "grid-template-columns: repeat(11, minmax(0, 1fr))" },
      { prop: "cols", value: "12", classes: "grid-template-columns: repeat(12, minmax(0, 1fr))" },
      { prop: "gap", value: "none", classes: "gap: 0" },
      { prop: "gap", value: "xs", classes: "gap: 0.25rem" },
      { prop: "gap", value: "sm", classes: "gap: 0.5rem" },
      { prop: "gap", value: "md (default)", classes: "gap: 1rem" },
      { prop: "gap", value: "lg", classes: "gap: 1.5rem" },
      { prop: "gap", value: "xl", classes: "gap: 2rem" },
      { prop: "gap", value: "2xl", classes: "gap: 3rem" },
      { prop: "gap", value: "3xl", classes: "gap: 4rem" },
      { prop: "flow", value: "row", classes: "grid-auto-flow: row" },
      { prop: "flow", value: "col", classes: "grid-auto-flow: column" },
      { prop: "flow", value: "dense", classes: "grid-auto-flow: dense" },
      { prop: "place-items", value: "center", classes: "place-items: center" },
      { prop: "responsive", value: "(present)", classes: "grid-template-columns: repeat(auto-fit, minmax(var(--lk-min-child-width, 250px), 1fr))" },
    ],
  },
  {
    name: "lk-spacer",
    tagline: "Flexible space that pushes siblings apart.",
    props: [
      { name: "size", type: 'GapSize | "auto"', default: "auto", desc: "Fixed height, or flex grow when auto" },
    ],
    examples: [
      { label: "Push apart", code: "<lk-row>\n  <span>Logo</span>\n  <lk-spacer></lk-spacer>\n  <button>Action</button>\n</lk-row>", output: "display: block; flex: 1 1 0%" },
      { label: "Fixed gap", code: "<lk-stack>\n  <div>Top</div>\n  <lk-spacer size=\"4\"></lk-spacer>\n  <div>Bottom</div>\n</lk-stack>", output: "display: block; flex: none; height: 1rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: block; flex: 1 1 0%" },
      { prop: "size", value: "auto (default)", classes: "flex: 1 1 0%" },
      { prop: "size", value: "xs", classes: "flex: none; height: 0.25rem" },
      { prop: "size", value: "sm", classes: "flex: none; height: 0.5rem" },
      { prop: "size", value: "md", classes: "flex: none; height: 1rem" },
      { prop: "size", value: "lg", classes: "flex: none; height: 1.5rem" },
      { prop: "size", value: "xl", classes: "flex: none; height: 2rem" },
      { prop: "size", value: "2xl", classes: "flex: none; height: 3rem" },
      { prop: "size", value: "3xl", classes: "flex: none; height: 4rem" },
    ],
  },
  {
    name: "lk-divider",
    tagline: "Visual separator between content sections.",
    props: [
      { name: "orientation", type: "horizontal | vertical", default: "horizontal", desc: "Line direction" },
      { name: "thickness", type: "thin | medium | thick", default: "thin (1px)", desc: "Line thickness" },
      { name: "--lk-divider-color", type: "color (custom prop)", default: "#e5e7eb", desc: "Line color (set inline via style)" },
    ],
    examples: [
      { label: "Section break", code: "<lk-stack>\n  <section>Section</section>\n  <lk-divider></lk-divider>\n  <section>Section</section>\n</lk-stack>", output: "display: block; width: 100%; border-top: 1px solid #e5e7eb" },
      { label: "Vertical", code: '<lk-row>\n  <span>Left</span>\n  <lk-divider orientation="vertical"></lk-divider>\n  <span>Right</span>\n</lk-row>', output: "display: block; width: auto; height: 100%; align-self: stretch; border-left: 1px solid #e5e7eb" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: block; width: 100%; border-top: 1px solid #e5e7eb" },
      { prop: "orientation", value: "horizontal (default)", classes: "width: 100%; border-top: 1px solid #e5e7eb" },
      { prop: "orientation", value: "vertical", classes: "width: auto; height: 100%; align-self: stretch; border-left: 1px solid #e5e7eb" },
      { prop: "thickness", value: "medium", classes: "border-top-width: 2px" },
      { prop: "thickness", value: "thick", classes: "border-top-width: 4px" },
    ],
  },
];

export const TUTORIAL_STEPS = [
  {
    title: "Center anything",
    description: "The most common layout need. lk-center centers content on both axes by default — pure CSS, no JavaScript.",
    code: "<lk-center full-height>\n  <h1>Hello World</h1>\n  <p>Perfectly centered</p>\n</lk-center>",
    challenge: "Try adding the full-height attribute to make it fill the screen.",
    hint: "full-height applies min-height: 100vh to take the full viewport height.",
  },
  {
    title: "Stack vertically",
    description: "lk-stack arranges children in a vertical column with consistent spacing.",
    code: '<lk-stack gap="lg">\n  <div>First item</div>\n  <div>Second item</div>\n  <div>Third item</div>\n</lk-stack>',
    challenge: 'Try changing gap to "xs", "sm", "md", "lg", "xl", or "2xl".',
    hint: "Each gap size maps to a CSS length: xs=0.25rem, sm=0.5rem, md=1rem, lg=1.5rem, xl=2rem, 2xl=3rem, 3xl=4rem.",
  },
  {
    title: "Rows and horizontal layout",
    description: "lk-row is identical to lk-stack but horizontal. Perfect for navbars, button groups, and inline elements.",
    code: '<lk-row gap="md">\n  <button>Save</button>\n  <button>Cancel</button>\n  <button>Delete</button>\n</lk-row>',
    challenge: 'Add justify="end" to push buttons to the right.',
    hint: "justify maps to justify-content (the main axis, horizontal for lk-row). Options: start, center, end, between, around, evenly.",
  },
  {
    title: "Spread apart",
    description: "lk-spread pushes children to opposite ends. Perfect for headers, footers, and toolbars.",
    code: '<lk-spread padding="md">\n  <span>Logo</span>\n  <nav>Menu</nav>\n</lk-spread>',
    challenge: 'This is equivalent to <lk-row justify="between"> — but lk-spread is the semantic tag for the pattern.',
    hint: "lk-spread always applies justify-content: space-between. A semantic shorthand for a very common pattern.",
  },
  {
    title: "Fill remaining space",
    description: "lk-box with the fill attribute expands to take all available space. Essential for sidebar layouts.",
    code: '<lk-row fill>\n  <lk-stack style="width: 16rem; border-right: 1px solid #e5e7eb">\n    <span>Sidebar</span>\n  </lk-stack>\n  <lk-box fill padding="lg">\n    <span>Main Content</span>\n  </lk-box>\n</lk-row>',
    challenge: "The fill attribute on lk-box applies flex: 1 1 0%. Try removing it and see how the output changes.",
    hint: "flex: 1 1 0% means the element grows to fill all available space.",
  },
  {
    title: "Grid layouts",
    description: "lk-grid creates CSS Grid layouts with simple column counts.",
    code: '<lk-grid cols="3" gap="md">\n  <div>Card 1</div>\n  <div>Card 2</div>\n  <div>Card 3</div>\n  <div>Card 4</div>\n  <div>Card 5</div>\n  <div>Card 6</div>\n</lk-grid>',
    challenge: 'Try changing cols to "2" or "4" and watch the grid-template-columns update.',
    hint: 'cols="n" maps to grid-template-columns: repeat(n, minmax(0, 1fr)).',
  },
  {
    title: "Composition",
    description: "The real power is composing tags together. A complete page layout, all in HTML.",
    code: '<lk-stack fill>\n  <lk-spread padding="md" style="border-bottom: 1px solid #e5e7eb">\n    <span>Logo</span>\n    <lk-row gap="sm">\n      <a href="#">Home</a>\n      <a href="#">About</a>\n    </lk-row>\n  </lk-spread>\n  <lk-row fill>\n    <lk-stack padding="md" style="width: 16rem; border-right: 1px solid #e5e7eb">\n      <span>Nav</span>\n    </lk-stack>\n    <lk-box fill padding="lg">\n      <lk-center>\n        <h1>Content</h1>\n      </lk-center>\n    </lk-box>\n  </lk-row>\n</lk-stack>',
    challenge: "This full page layout uses 0 raw flexbox/grid CSS in your markup. Every structural decision is readable at a glance.",
    hint: "Notice how each tag name tells you exactly what layout behavior to expect.",
  },
];

export const LINT_RULES = [
  {
    id: "LK001",
    name: "redundant-center-axes",
    description: "Using both horizontal and vertical on lk-center is redundant — lk-center already centers both axes by default.",
    example: { bad: "<lk-center horizontal vertical>", good: "<lk-center>" },
  },
  {
    id: "LK002",
    name: "prefer-spread",
    description: 'lk-row with justify="between" should use <lk-spread> for better semantics.',
    example: { bad: '<lk-row justify="between">', good: "<lk-spread>" },
  },
  {
    id: "LK003",
    name: "conflicting-center-align",
    description: "The center attribute overrides align. Using both creates confusion.",
    example: { bad: '<lk-stack center align="start">', good: "<lk-stack center>" },
  },
  {
    id: "LK004",
    name: "unnecessary-gap-none",
    description: 'gap="none" applies gap: 0, which has no visual effect over an already-zero gap.',
    example: { bad: '<lk-stack gap="none">', good: "<lk-stack>" },
  },
  {
    id: "LK005",
    name: "raw-css-layout",
    description: "Detects raw flexbox layout CSS that should use semantic lk-* tags instead.",
    example: { bad: '<div style="display: flex; flex-direction: column; align-items: center; justify-content: center">', good: "<lk-center>" },
  },
  {
    id: "LK006",
    name: "nested-center",
    description: "Multiple nested lk-center tags are usually redundant.",
    example: { bad: "<lk-center><lk-center>...</lk-center></lk-center>", good: "<lk-center>...</lk-center>" },
  },
];
