export interface ComponentDoc {
  name: string;
  tagline: string;
  props: { name: string; type: string; default: string; desc: string }[];
  examples: { label: string; code: string; output: string }[];
  classMap: { prop: string; value: string; classes: string }[];
}

export const COMPONENT_DOCS: ComponentDoc[] = [
  {
    name: "Center",
    tagline: "Center content on both axes. The #1 CSS pain point, solved.",
    props: [
      { name: "fill", type: "boolean", default: "false", desc: "Grow to fill available space in parent" },
      { name: "fullHeight", type: "boolean", default: "false", desc: "Force a minimum full-viewport height" },
      { name: "horizontal", type: "boolean", default: "false", desc: "Center only on x-axis" },
      { name: "vertical", type: "boolean", default: "false", desc: "Center only on y-axis" },
      { name: "inline", type: "boolean", default: "false", desc: "Use inline-flex instead of flex" },
      { name: "as", type: "ElementType", default: '"div"', desc: "Render as different HTML element" },
      { name: "className", type: "string", default: '""', desc: "Additional CSS classes (passed through)" },
    ],
    examples: [
      { label: "Basic center", code: "<Center>\n  <h1>Centered</h1>\n</Center>", output: "display: flex; flex-direction: column; align-items: center; justify-content: center" },
      { label: "Full page", code: "<Center fullHeight>\n  <LoginForm />\n</Center>", output: "display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh" },
      { label: "Horizontal only", code: "<Center horizontal>\n  <Nav />\n</Center>", output: "display: flex; flex-direction: column; align-items: center" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: column" },
      { prop: "default", value: "(no axis props)", classes: "align-items: center; justify-content: center" },
      { prop: "fill", value: "true", classes: "flex: 1 1 0%" },
      { prop: "fullHeight", value: "true", classes: "min-height: 100vh" },
      { prop: "horizontal", value: "true", classes: "align-items: center" },
      { prop: "vertical", value: "true", classes: "justify-content: center" },
      { prop: "inline", value: "true", classes: "display: inline-flex (replaces flex)" },
    ],
  },
  {
    name: "Stack",
    tagline: "Vertical flex column with consistent spacing.",
    props: [
      { name: "gap", type: "GapSize", default: '"md"', desc: "Space between children" },
      { name: "align", type: "Align", default: '"stretch"', desc: "Cross-axis alignment" },
      { name: "justify", type: "Justify", default: '"start"', desc: "Main-axis alignment" },
      { name: "center", type: "boolean", default: "false", desc: "Center both axes (shorthand)" },
      { name: "fill", type: "boolean", default: "false", desc: "Full viewport height" },
      { name: "padding", type: "Padding", default: '"none"', desc: "Internal padding" },
      { name: "wrap", type: "boolean", default: "false", desc: "Allow wrapping" },
      { name: "className", type: "string", default: '""', desc: "Additional CSS classes (passed through)" },
    ],
    examples: [
      { label: "Default stack", code: "<Stack>\n  <Item />\n  <Item />\n</Stack>", output: "display: flex; flex-direction: column; gap: 1rem; align-items: stretch; justify-content: flex-start" },
      { label: "Centered stack", code: '<Stack center gap="lg">\n  <Avatar />\n  <Name />\n</Stack>', output: "display: flex; flex-direction: column; gap: 1.5rem; align-items: center; justify-content: center" },
      { label: "With padding", code: '<Stack padding="lg" gap="sm">\n  <Input />\n  <Input />\n</Stack>', output: "display: flex; flex-direction: column; gap: 0.5rem; align-items: stretch; justify-content: flex-start; padding: 1.5rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: column" },
      { prop: "gap", value: '"none"', classes: "gap: 0" },
      { prop: "gap", value: '"xs"', classes: "gap: 0.25rem" },
      { prop: "gap", value: '"sm"', classes: "gap: 0.5rem" },
      { prop: "gap", value: '"md" (default)', classes: "gap: 1rem" },
      { prop: "gap", value: '"lg"', classes: "gap: 1.5rem" },
      { prop: "gap", value: '"xl"', classes: "gap: 2rem" },
      { prop: "gap", value: '"2xl"', classes: "gap: 3rem" },
      { prop: "gap", value: '"3xl"', classes: "gap: 4rem" },
      { prop: "align", value: '"start"', classes: "align-items: flex-start" },
      { prop: "align", value: '"center"', classes: "align-items: center" },
      { prop: "align", value: '"end"', classes: "align-items: flex-end" },
      { prop: "align", value: '"stretch" (default)', classes: "align-items: stretch" },
      { prop: "align", value: '"baseline"', classes: "align-items: baseline" },
      { prop: "justify", value: '"start" (default)', classes: "justify-content: flex-start" },
      { prop: "justify", value: '"center"', classes: "justify-content: center" },
      { prop: "justify", value: '"end"', classes: "justify-content: flex-end" },
      { prop: "justify", value: '"between"', classes: "justify-content: space-between" },
      { prop: "justify", value: '"around"', classes: "justify-content: space-around" },
      { prop: "justify", value: '"evenly"', classes: "justify-content: space-evenly" },
      { prop: "center", value: "true", classes: "align-items: center; justify-content: center" },
      { prop: "fill", value: "true", classes: "min-height: 100vh" },
      { prop: "wrap", value: "true", classes: "flex-wrap: wrap" },
      { prop: "padding", value: '"xs"', classes: "padding: 0.25rem" },
      { prop: "padding", value: '"sm"', classes: "padding: 0.5rem" },
      { prop: "padding", value: '"md"', classes: "padding: 1rem" },
      { prop: "padding", value: '"lg"', classes: "padding: 1.5rem" },
      { prop: "padding", value: '"xl"', classes: "padding: 2rem" },
      { prop: "padding", value: '"2xl"', classes: "padding: 3rem" },
    ],
  },
  {
    name: "Row",
    tagline: "Horizontal flex row. Same API as Stack, different axis.",
    props: [
      { name: "gap", type: "GapSize", default: '"md"', desc: "Space between children" },
      { name: "align", type: "Align", default: '"center"', desc: "Cross-axis alignment" },
      { name: "justify", type: "Justify", default: '"start"', desc: "Main-axis alignment" },
      { name: "center", type: "boolean", default: "false", desc: "Center both axes" },
      { name: "wrap", type: "boolean", default: "false", desc: "Allow wrapping" },
      { name: "reverse", type: "boolean", default: "false", desc: "Reverse direction" },
      { name: "className", type: "string", default: '""', desc: "Additional CSS classes (passed through)" },
    ],
    examples: [
      { label: "Button group", code: '<Row gap="sm">\n  <Button>Save</Button>\n  <Button>Cancel</Button>\n</Row>', output: "display: flex; flex-direction: row; gap: 0.5rem; align-items: center; justify-content: flex-start" },
      { label: "Nav bar", code: '<Row justify="between">\n  <Logo />\n  <Menu />\n</Row>', output: "display: flex; flex-direction: row; gap: 1rem; align-items: center; justify-content: space-between" },
      { label: "Wrapped tags", code: '<Row wrap gap="xs">\n  <Tag /><Tag /><Tag />\n</Row>', output: "display: flex; flex-direction: row; gap: 0.25rem; align-items: center; justify-content: flex-start; flex-wrap: wrap" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: row" },
      { prop: "gap", value: '"none"', classes: "gap: 0" },
      { prop: "gap", value: '"xs"', classes: "gap: 0.25rem" },
      { prop: "gap", value: '"sm"', classes: "gap: 0.5rem" },
      { prop: "gap", value: '"md" (default)', classes: "gap: 1rem" },
      { prop: "gap", value: '"lg"', classes: "gap: 1.5rem" },
      { prop: "gap", value: '"xl"', classes: "gap: 2rem" },
      { prop: "gap", value: '"2xl"', classes: "gap: 3rem" },
      { prop: "gap", value: '"3xl"', classes: "gap: 4rem" },
      { prop: "align", value: '"start"', classes: "align-items: flex-start" },
      { prop: "align", value: '"center" (default)', classes: "align-items: center" },
      { prop: "align", value: '"end"', classes: "align-items: flex-end" },
      { prop: "align", value: '"stretch"', classes: "align-items: stretch" },
      { prop: "align", value: '"baseline"', classes: "align-items: baseline" },
      { prop: "justify", value: '"start" (default)', classes: "justify-content: flex-start" },
      { prop: "justify", value: '"center"', classes: "justify-content: center" },
      { prop: "justify", value: '"end"', classes: "justify-content: flex-end" },
      { prop: "justify", value: '"between"', classes: "justify-content: space-between" },
      { prop: "justify", value: '"around"', classes: "justify-content: space-around" },
      { prop: "justify", value: '"evenly"', classes: "justify-content: space-evenly" },
      { prop: "center", value: "true", classes: "align-items: center; justify-content: center" },
      { prop: "wrap", value: "true", classes: "flex-wrap: wrap" },
      { prop: "reverse", value: "true", classes: "flex-direction: row-reverse" },
      { prop: "padding", value: '"xs"', classes: "padding: 0.25rem" },
      { prop: "padding", value: '"sm"', classes: "padding: 0.5rem" },
      { prop: "padding", value: '"md"', classes: "padding: 1rem" },
      { prop: "padding", value: '"lg"', classes: "padding: 1.5rem" },
      { prop: "padding", value: '"xl"', classes: "padding: 2rem" },
      { prop: "padding", value: '"2xl"', classes: "padding: 3rem" },
    ],
  },
  {
    name: "Box",
    tagline: "Generic container. Fills space, holds content.",
    props: [
      { name: "fill", type: "boolean", default: "false", desc: "flex-1 (expand to fill)" },
      { name: "padding", type: "Padding", default: '"none"', desc: "Internal padding" },
      { name: "center", type: "boolean", default: "false", desc: "Center content" },
      { name: "className", type: "string", default: '""', desc: "Additional CSS classes (passed through)" },
    ],
    examples: [
      { label: "Fill space", code: "<Box fill>\n  <Content />\n</Box>", output: "flex: 1 1 0%" },
      { label: "Padded fill", code: '<Box fill padding="lg">\n  <Content />\n</Box>', output: "flex: 1 1 0%; padding: 1.5rem" },
      { label: "Centered box", code: "<Box center>\n  <Spinner />\n</Box>", output: "display: flex; align-items: center; justify-content: center" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "(no base classes)" },
      { prop: "fill", value: "true", classes: "flex: 1 1 0%" },
      { prop: "center", value: "true", classes: "display: flex; align-items: center; justify-content: center" },
      { prop: "padding", value: '"xs"', classes: "padding: 0.25rem" },
      { prop: "padding", value: '"sm"', classes: "padding: 0.5rem" },
      { prop: "padding", value: '"md"', classes: "padding: 1rem" },
      { prop: "padding", value: '"lg"', classes: "padding: 1.5rem" },
      { prop: "padding", value: '"xl"', classes: "padding: 2rem" },
      { prop: "padding", value: '"2xl"', classes: "padding: 3rem" },
    ],
  },
  {
    name: "Spread",
    tagline: "Push children to opposite ends. Headers, footers, toolbars.",
    props: [
      { name: "align", type: "Align", default: '"center"', desc: "Cross-axis alignment" },
      { name: "padding", type: "Padding", default: '"none"', desc: "Internal padding" },
      { name: "className", type: "string", default: '""', desc: "Additional CSS classes (passed through)" },
    ],
    examples: [
      { label: "Header", code: "<Spread>\n  <Logo />\n  <Nav />\n</Spread>", output: "display: flex; flex-direction: row; justify-content: space-between; align-items: center" },
      { label: "Footer", code: '<Spread padding="sm">\n  <Copyright />\n  <Links />\n</Spread>', output: "display: flex; flex-direction: row; justify-content: space-between; align-items: center; padding: 0.5rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: flex; flex-direction: row; justify-content: space-between" },
      { prop: "align", value: '"start"', classes: "align-items: flex-start" },
      { prop: "align", value: '"center" (default)', classes: "align-items: center" },
      { prop: "align", value: '"end"', classes: "align-items: flex-end" },
      { prop: "align", value: '"stretch"', classes: "align-items: stretch" },
      { prop: "align", value: '"baseline"', classes: "align-items: baseline" },
      { prop: "padding", value: '"xs"', classes: "padding: 0.25rem" },
      { prop: "padding", value: '"sm"', classes: "padding: 0.5rem" },
      { prop: "padding", value: '"md"', classes: "padding: 1rem" },
      { prop: "padding", value: '"lg"', classes: "padding: 1.5rem" },
      { prop: "padding", value: '"xl"', classes: "padding: 2rem" },
      { prop: "padding", value: '"2xl"', classes: "padding: 3rem" },
    ],
  },
  {
    name: "Grid",
    tagline: "CSS Grid with simple column counts.",
    props: [
      { name: "cols", type: "1-12", default: "1", desc: "Number of columns" },
      { name: "gap", type: "GapSize", default: '"md"', desc: "Gap between grid items" },
      { name: "responsive", type: "boolean", default: "false", desc: "Auto-responsive with auto-fit" },
      { name: "minChildWidth", type: "string", default: '"250px"', desc: "Min child width when responsive" },
      { name: "className", type: "string", default: '""', desc: "Additional CSS classes (passed through)" },
    ],
    examples: [
      { label: "3-column", code: '<Grid cols={3} gap="md">\n  <Card /><Card /><Card />\n</Grid>', output: "display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 1rem" },
      { label: "Dashboard", code: '<Grid cols={4} gap="sm">\n  <Stat /><Stat /><Stat /><Stat />\n</Grid>', output: "display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 0.5rem" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "display: grid" },
      { prop: "cols", value: "1", classes: "grid-template-columns: repeat(1, minmax(0, 1fr))" },
      { prop: "cols", value: "2", classes: "grid-template-columns: repeat(2, minmax(0, 1fr))" },
      { prop: "cols", value: "3", classes: "grid-template-columns: repeat(3, minmax(0, 1fr))" },
      { prop: "cols", value: "4", classes: "grid-template-columns: repeat(4, minmax(0, 1fr))" },
      { prop: "cols", value: "5", classes: "grid-template-columns: repeat(5, minmax(0, 1fr))" },
      { prop: "cols", value: "6", classes: "grid-template-columns: repeat(6, minmax(0, 1fr))" },
      { prop: "cols", value: "7", classes: "grid-template-columns: repeat(7, minmax(0, 1fr))" },
      { prop: "cols", value: "8", classes: "grid-template-columns: repeat(8, minmax(0, 1fr))" },
      { prop: "cols", value: "9", classes: "grid-template-columns: repeat(9, minmax(0, 1fr))" },
      { prop: "cols", value: "10", classes: "grid-template-columns: repeat(10, minmax(0, 1fr))" },
      { prop: "cols", value: "11", classes: "grid-template-columns: repeat(11, minmax(0, 1fr))" },
      { prop: "cols", value: "12", classes: "grid-template-columns: repeat(12, minmax(0, 1fr))" },
      { prop: "gap", value: '"none"', classes: "gap: 0" },
      { prop: "gap", value: '"xs"', classes: "gap: 0.25rem" },
      { prop: "gap", value: '"sm"', classes: "gap: 0.5rem" },
      { prop: "gap", value: '"md" (default)', classes: "gap: 1rem" },
      { prop: "gap", value: '"lg"', classes: "gap: 1.5rem" },
      { prop: "gap", value: '"xl"', classes: "gap: 2rem" },
      { prop: "gap", value: '"2xl"', classes: "gap: 3rem" },
      { prop: "gap", value: '"3xl"', classes: "gap: 4rem" },
      { prop: "responsive", value: "true", classes: "grid-template-columns: repeat(auto-fit, minmax(var(--min-child-width), 1fr))" },
    ],
  },
  {
    name: "Spacer",
    tagline: "Flexible space that pushes siblings apart.",
    props: [
      { name: "size", type: 'GapSize | "auto"', default: '"auto"', desc: "Fixed size or flex grow" },
    ],
    examples: [
      { label: "Push apart", code: "<Row>\n  <Logo />\n  <Spacer />\n  <Button />\n</Row>", output: "flex: 1 1 0%" },
    ],
    classMap: [
      { prop: "base", value: "—", classes: "flex: 1 1 0%" },
      { prop: "size", value: '"auto" (default)', classes: "flex: 1 1 0%" },
      { prop: "size", value: '"xs"', classes: "height: 0.25rem" },
      { prop: "size", value: '"sm"', classes: "height: 0.5rem" },
      { prop: "size", value: '"md"', classes: "height: 1rem" },
      { prop: "size", value: '"lg"', classes: "height: 1.5rem" },
      { prop: "size", value: '"xl"', classes: "height: 2rem" },
      { prop: "size", value: '"2xl"', classes: "height: 3rem" },
      { prop: "size", value: '"3xl"', classes: "height: 4rem" },
    ],
  },
  {
    name: "Divider",
    tagline: "Visual separator between content sections.",
    props: [
      { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', desc: "Line direction" },
      { name: "color", type: "string", default: '"#e5e7eb"', desc: "CSS color" },
      { name: "className", type: "string", default: '""', desc: "Additional CSS classes (passed through)" },
    ],
    examples: [
      { label: "Section break", code: "<Stack>\n  <Section />\n  <Divider />\n  <Section />\n</Stack>", output: "width: 100%; border-top: 1px solid #e5e7eb" },
    ],
    classMap: [
      { prop: "orientation", value: '"horizontal" (default)', classes: "width: 100%; border-top: 1px solid #e5e7eb" },
      { prop: "orientation", value: '"vertical"', classes: "height: 100%; border-left: 1px solid #e5e7eb" },
    ],
  },
];

export const TUTORIAL_STEPS = [
  {
    title: "Center anything",
    description: "The most common layout need. Center centers content on both axes by default.",
    code: "<Center fill>\n  <h1>Hello World</h1>\n  <p>Perfectly centered</p>\n</Center>",
    challenge: "Try adding the fill prop to make it full-screen.",
    hint: "fill adds min-h-screen to take the full viewport height.",
  },
  {
    title: "Stack vertically",
    description: "Stack arranges children in a vertical column with consistent spacing.",
    code: '<Stack gap="lg">\n  <div>First item</div>\n  <div>Second item</div>\n  <div>Third item</div>\n</Stack>',
    challenge: 'Try changing gap to "xs", "sm", "md", "lg", "xl", or "2xl".',
    hint: "Each gap size maps to a CSS length: xs=0.25rem, sm=0.5rem, md=1rem, lg=1.5rem, xl=2rem, 2xl=3rem, 3xl=4rem.",
  },
  {
    title: "Rows and horizontal layout",
    description: "Row is identical to Stack but horizontal. Perfect for navbars, button groups, and inline elements.",
    code: '<Row gap="md">\n  <button>Save</button>\n  <button>Cancel</button>\n  <button>Delete</button>\n</Row>',
    challenge: 'Add justify="end" to push buttons to the right.',
    hint: "justify controls the main axis (horizontal for Row). Options: start, center, end, between, around, evenly.",
  },
  {
    title: "Spread apart",
    description: "Spread pushes children to opposite ends. Perfect for headers, footers, and toolbars.",
    code: '<Spread padding="md">\n  <span>Logo</span>\n  <nav>Menu</nav>\n</Spread>',
    challenge: 'This is equivalent to <Row justify="between"> — the linter will suggest Spread when it sees that pattern.',
    hint: "Spread always applies justify-content: space-between. A semantic shorthand for a very common pattern.",
  },
  {
    title: "Fill remaining space",
    description: "Box with fill expands to take all available space. Essential for sidebar layouts.",
    code: '<Row fill>\n  <Stack className="w-64 border-r">\n    <span>Sidebar</span>\n  </Stack>\n  <Box fill padding="lg">\n    <span>Main Content</span>\n  </Box>\n</Row>',
    challenge: "The fill prop on Box compiles to flex: 1 1 0%. Try removing it and see how the output changes.",
    hint: "flex: 1 1 0% means the element grows to fill all available space.",
  },
  {
    title: "Grid layouts",
    description: "Grid creates CSS Grid layouts with simple column counts.",
    code: '<Grid cols={3} gap="md">\n  <div>Card 1</div>\n  <div>Card 2</div>\n  <div>Card 3</div>\n  <div>Card 4</div>\n  <div>Card 5</div>\n  <div>Card 6</div>\n</Grid>',
    challenge: "Try changing cols to {2} or {4} and watch the grid-template-columns update.",
    hint: "cols={n} maps to grid-template-columns: repeat(n, minmax(0, 1fr)).",
  },
  {
    title: "Composition",
    description: "The real power is composing primitives together. A complete page layout.",
    code: '<Stack fill>\n  <Spread padding="md" className="border-b">\n    <span>Logo</span>\n    <Row gap="sm">\n      <a>Home</a>\n      <a>About</a>\n    </Row>\n  </Spread>\n  <Row className="flex-1">\n    <Stack className="w-64 border-r" padding="md">\n      <span>Nav</span>\n    </Stack>\n    <Box fill padding="lg">\n      <Center>\n        <h1>Content</h1>\n      </Center>\n    </Box>\n  </Row>\n</Stack>',
    challenge: "This full page layout uses 0 raw flexbox/grid CSS. Every structural decision is readable at a glance.",
    hint: "Notice how each component name tells you exactly what layout behavior to expect.",
  },
];

export const LINT_RULES = [
  {
    id: "LK001",
    name: "redundant-center-axes",
    description: "Using both horizontal and vertical on Center is redundant — Center already centers both axes by default.",
    example: { bad: "<Center horizontal vertical>", good: "<Center>" },
  },
  {
    id: "LK002",
    name: "prefer-spread",
    description: 'Row with justify="between" should use <Spread> for better semantics.',
    example: { bad: '<Row justify="between">', good: "<Spread>" },
  },
  {
    id: "LK003",
    name: "conflicting-center-align",
    description: "The center prop overrides align. Using both creates confusion.",
    example: { bad: '<Stack center align="start">', good: "<Stack center>" },
  },
  {
    id: "LK004",
    name: "unnecessary-gap-none",
    description: 'gap="none" compiles to gap-0, which has no visual effect.',
    example: { bad: '<Stack gap="none">', good: "<Stack>" },
  },
  {
    id: "LK005",
    name: "raw-tailwind-layout",
    description: "Detects raw Tailwind layout classes that should use LayoutKit components instead.",
    example: { bad: '<div className="flex flex-col items-center justify-center">', good: "<Center>" },
  },
  {
    id: "LK006",
    name: "nested-center",
    description: "Multiple nested Center components are usually redundant.",
    example: { bad: "<Center><Center>...</Center></Center>", good: "<Center>...</Center>" },
  },
];
